export type EventChain={device_id:string;index:number;previous_hash:string;event_hash:string;signature:string};
const DB="private-direct-event-chains",STORE="heads";
function encode(bytes:Uint8Array){let value="";bytes.forEach(byte=>value+=String.fromCharCode(byte));return btoa(value).replace(/=+$/,"")}
async function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function head(key:string){const db=await database();const value=await new Promise<{index:number;hash:string}|undefined>((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return value??{index:0,hash:""}}
async function save(key:string,value:{index:number;hash:string}){const db=await database();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
export async function createEventChain(username:string,contactID:number,messageID:string,ciphertext:Record<string,unknown>,deviceID:string,sign:(hash:string)=>Promise<string>):Promise<EventChain>{const key=`${username}:${contactID}:${deviceID}`;const run=async()=>{const previous=await head(key);const index=previous.index+1;const material=`${messageID}|${contactID}|${JSON.stringify(ciphertext)}|${index}|${previous.hash}`;const event_hash=encode(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(material))));const signature=await sign(event_hash);await save(key,{index,hash:event_hash});return{device_id:deviceID,index,previous_hash:previous.hash,event_hash,signature}};return navigator.locks?navigator.locks.request(`private-direct-chain-${key}`,run):run()}
export function clearEventChains(){indexedDB.deleteDatabase(DB)}

function decode(value:string){const padded=value+"=".repeat((4-value.length%4)%4);return Uint8Array.from(atob(padded),char=>char.charCodeAt(0))}
export async function validateEventPage(messages:Array<{id:string;recipient_id:number;ciphertext:Record<string,unknown>;chain?:EventChain&{device_keys:{keys?:Record<string,string>}}}>){const heads=new Map<string,{index:number;hash:string}>();for(const message of messages){if(!message.chain)continue;const chain=message.chain;const material=`${message.id}|${message.recipient_id}|${JSON.stringify(message.ciphertext)}|${chain.index}|${chain.previous_hash}`;const expected=encode(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(material))));if(expected!==chain.event_hash)throw new Error("event_chain_altered");const publicKey=chain.device_keys.keys?.[`ed25519:${chain.device_id}`];if(!publicKey)throw new Error("event_chain_key_missing");const key=await crypto.subtle.importKey("raw",decode(publicKey),{name:"Ed25519"},false,["verify"]);if(!await crypto.subtle.verify({name:"Ed25519"},key,decode(chain.signature),new TextEncoder().encode(chain.event_hash)))throw new Error("event_chain_signature_invalid");const previous=heads.get(chain.device_id);if(previous&&(chain.index!==previous.index+1||chain.previous_hash!==previous.hash))throw new Error("event_chain_gap");heads.set(chain.device_id,{index:chain.index,hash:chain.event_hash})}}
